# /// script
# requires-python = ">=3.13"
# dependencies = []
# ///
"""The status report is current (ADR-0028 §3).

Runs as `make gate-status`. Standard library only, so `uv run tools/check_status.py` and
`python3 tools/check_status.py` both work without the project installed.

`docs/status.md` is the one file that says where the project stands and what is needed from
the owner. Section 3, *Needed from the owner*, says where the list is and does not hold it:
the list is generated from the open needs and decision requests of the register, printed by
`--print` (`make status`) and carried as the last section of every pull request description.
The rest is written by hand by every pull request that changes the state of the project.

Checks:

1. the file exists, starts with `# Status`, and has the five sections in order, none empty, no
   placeholder;
2. the milestone named first in section 1 is a milestone of docs/roadmap.md;
3. the file stores no line that every pull request rewrites: no `**As of:**` date and no running
   `**Decided since …**` list. Both were edited by every pull request that touched the file, so
   any two such pull requests conflicted on them (DEC-0027). The date of the status is the date
   of its last commit; what was decided when is the register's index. A decision the status
   has not accounted for is caught by check 5, because every record lives under docs/decisions/;
4. section 3 stores no list: it points at `make status`, which prints what the register
   generates — every open need and decision request, the most urgent first. A generated list
   in a committed file conflicts between any two pull requests that touch the register, and
   is a stale copy the moment either merges (DEC-0026);
5. against a base (`--base`, default `origin/main`, then `main`): a change to the state of the
   project — under src/, workers/, blueprints/, contracts/, deploy/, migrations/, tools/,
   docs/adr/, docs/decisions/ or docs/roadmap.md — comes with a change to docs/status.md;
6. with --pr-body: the last section of the pull request description, `## Needed from the
   owner`, carries what the register generates, so that the owner sees it without opening a
   file. The description is the one place the generated list is carried: it is written from
   the branch it describes and never merged with another.

`--print` prints the list (`make status`). Nothing writes it into a file.

A register with nothing open generates "nothing is open" and says so. The last line is the
duration.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATUS = ROOT / "docs" / "status.md"
ROADMAP = ROOT / "docs" / "roadmap.md"
REGISTER = ROOT / "docs" / "decisions"
OPEN = REGISTER / "open"

SECTIONS = [
    "1. Where the project is",
    "2. The next pull requests",
    "3. Needed from the owner",
    "4. Blocked",
    "5. Promises not yet kept",
]
PR_SECTION = "needed from the owner"
BEGIN = (
    "<!-- generated by tools/check_status.py from docs/decisions/open/; `make status` prints it -->"
)
END = "<!-- end generated -->"
# Section 3 of the file says where the list is instead of holding it (DEC-0026).
POINTER = "`make status`"
STORED_ROW = re.compile(r"^\|\s*(?:NEED|DEC)-\d{4}\s*\|", re.MULTILINE)
NOTHING_OPEN = "Nothing is open: no needs request and no decision request waits for the owner."
COLUMNS = "| Record | What | Needed by | Kind | Issue |\n|---|---|---|---|---|"

# What changes the state of the project: a change here without a change to the status file is
# a status that no longer says where the project is.
STATE = re.compile(
    r"^(src|workers|blueprints|contracts|deploy|migrations|tools|docs/adr|docs/decisions)/"
    r"|^docs/roadmap\.md$"
)
STATUS_PATH = "docs/status.md"

TITLE = re.compile(r"^# (DEC|NEED)-(\d{4}) — (.+)$")
FIELD = re.compile(r"^\*\*([A-Za-z ]+):\*\*\s*(.*)$")
MILESTONE = re.compile(r"`(\d+\.\d+\.\d+)`")
ISSUE_REF = re.compile(r"#\d+\b")
PLACEHOLDER = re.compile(r"<[^>\n]+>|\b(?:TODO|TBD|FIXME|XXX)\b|…")
# Lines every pull request rewrote, and therefore the lines any two of them conflicted on
# (DEC-0027): a stored date and a running list of what was decided since the last version.
REWRITTEN = re.compile(r"^\*\*(As of|Decided since[^*]*):\*\*", re.MULTILINE)


@dataclass
class Report:
    passed: int = 0
    failures: list[str] = field(default_factory=list)

    def ok(self, what: str) -> None:
        self.passed += 1
        print(f"  ok   {what}")

    def fail(self, what: str, why: str) -> None:
        self.failures.append(f"{what}: {why}")
        print(f"  FAIL {what}\n       {why}")


@dataclass(frozen=True)
class Open:
    """One open record: a need or a decision request, as the owner sees it."""

    identifier: str
    title: str
    needed_by: str
    kind: str
    issue: str

    @property
    def urgency(self) -> tuple[str, int, str]:
        # The earliest date first; a BLOCKING decision before anything else on the same day.
        return (self.needed_by, 0 if self.kind == "BLOCKING" else 1, self.identifier)


# --- parsing -------------------------------------------------------------------------------------


def strip_comments(text: str) -> str:
    return re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)


def strip_code(text: str) -> str:
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
    return re.sub(r"`[^`\n]*`", "", text)


def header_fields(text: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for line in text.splitlines()[1:]:
        if line.startswith("## "):
            break
        if match := FIELD.match(line):
            fields[match.group(1)] = match.group(2).strip()
    return fields


def sections(text: str) -> dict[str, str]:
    found: dict[str, str] = {}
    current: str | None = None
    buffer: list[str] = []
    for line in text.splitlines():
        if line.startswith("## "):
            if current is not None:
                found[current] = "\n".join(buffer).strip()
            current = line[3:].strip()
            buffer = []
        elif current is not None:
            buffer.append(line)
    if current is not None:
        found[current] = "\n".join(buffer).strip()
    return found


# --- the register --------------------------------------------------------------------------------


def open_records() -> list[Open]:
    """Every open need and decision request, the most urgent first."""
    found: list[Open] = []
    if not OPEN.is_dir():
        return found
    for path in sorted(OPEN.glob("*.md")):
        text = strip_comments(path.read_text(encoding="utf-8"))
        first = text.splitlines()[0] if text else ""
        match = TITLE.match(first)
        if match is None:
            continue
        prefix, number, title = match.groups()
        fields = header_fields(text)
        kind = fields.get("Category" if prefix == "DEC" else "Kind", "?")
        issue = ISSUE_REF.search(fields.get("Issue", ""))
        found.append(
            Open(
                f"{prefix}-{number}",
                title.strip(),
                fields.get("Needed by", "?"),
                kind,
                issue.group(0) if issue else "no issue",
            )
        )
    return sorted(found, key=lambda record: record.urgency)


def generated(records: list[Open]) -> str:
    if not records:
        return NOTHING_OPEN
    rows = [
        f"| {r.identifier} | {r.title} | {r.needed_by} | {r.kind} | {r.issue} |" for r in records
    ]
    return "\n".join([COLUMNS, *rows])


# --- the generated list ------------------------------------------------------------------------


def normalise(text: str) -> str:
    return " ".join(text.split())


def printable(content: str) -> str:
    """The list as it goes into a pull request description, between its markers."""
    return f"{BEGIN}\n{content}\n{END}"


# --- git -----------------------------------------------------------------------------------------


def git(*args: str) -> str:
    # A fixed executable name and arguments assembled here, not from input: nothing untrusted.
    result = subprocess.run(  # noqa: S603
        ["git", *args],  # noqa: S607
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout


def resolve_base(requested: str | None) -> str | None:
    for candidate in [requested] if requested else ["origin/main", "main"]:
        try:
            git("rev-parse", "--verify", "--quiet", f"{candidate}^{{commit}}")
        except RuntimeError:
            continue
        return candidate
    return None


def changed_files(base: str) -> set[str]:
    committed = git("diff", "--name-only", f"{base}...HEAD").split()
    working = git("status", "--porcelain", "--untracked-files=all")
    uncommitted = [line[3:].split(" -> ")[-1] for line in working.splitlines() if line.strip()]
    return set(committed) | set(uncommitted)


# --- checks --------------------------------------------------------------------------------------


def check_shape(text: str, report: Report) -> dict[str, str]:
    print("shape")
    problems: list[str] = []
    lines = text.splitlines()
    if not lines or lines[0].strip() != "# Status":
        problems.append("the first line is not `# Status`")
    for match in REWRITTEN.finditer(text):
        problems.append(
            f"`**{match.group(1)}:**` is a line every pull request rewrites, and two pull "
            "requests conflict on it; the date is the file's last commit, and what was decided "
            "when is docs/decisions/README.md (DEC-0027)"
        )
    found = sections(text)
    present = list(found)
    if present != SECTIONS:
        missing = [name for name in SECTIONS if name not in present]
        unexpected = [name for name in present if name not in SECTIONS]
        if missing:
            problems.append("missing section(s): " + ", ".join(f"`## {m}`" for m in missing))
        if unexpected:
            problems.append("unexpected section(s): " + ", ".join(f"`## {u}`" for u in unexpected))
        if not missing and not unexpected:
            problems.append("sections are out of order")
    for name, body in found.items():
        if not body:
            problems.append(f"`## {name}` is empty")
        elif hit := PLACEHOLDER.search(strip_code(strip_comments(body))):
            problems.append(f"`## {name}` keeps a placeholder: {hit.group(0)!r}")
    if problems:
        report.fail(STATUS_PATH, "; ".join(problems))
    else:
        report.ok(f"{STATUS_PATH}: `# Status`, five sections in order, no rewritten line")
    return found


def check_milestone(found: dict[str, str], report: Report) -> None:
    print("milestone")
    body = found.get(SECTIONS[0], "")
    match = MILESTONE.search(body)
    if match is None:
        report.fail(STATUS_PATH, f"`## {SECTIONS[0]}` names no milestone (`x.y.z` in backticks)")
        return
    milestone = match.group(1)
    roadmap = ROADMAP.read_text(encoding="utf-8") if ROADMAP.exists() else ""
    if re.search(rf"^### `{re.escape(milestone)}`", roadmap, re.MULTILINE):
        report.ok(f"`{milestone}` is a milestone of {ROADMAP.relative_to(ROOT)}")
    else:
        report.fail(
            STATUS_PATH,
            f"`{milestone}` is not a milestone heading of {ROADMAP.relative_to(ROOT)}",
        )


def check_pointer(found: dict[str, str], report: Report) -> None:
    print("needed from the owner")
    body = found.get(SECTIONS[2], "")
    if STORED_ROW.search(body) or BEGIN.split(";")[0] in body:
        report.fail(
            STATUS_PATH,
            "section 3 stores the list; it points at `make status` instead, because a stored "
            "list conflicts between pull requests and goes stale when one merges (DEC-0026)",
        )
    elif POINTER not in body:
        report.fail(STATUS_PATH, f"section 3 does not say where the list is ({POINTER})")
    else:
        report.ok(f"section 3 points at {POINTER} and stores no list")


def check_freshness(base: str | None, report: Report) -> None:
    print("freshness")
    resolved = resolve_base(base)
    if resolved is None:
        report.fail("base", f"{base or 'origin/main or main'} not found; cannot tell what changed")
        return
    changed = changed_files(resolved)
    state = sorted(path for path in changed if STATE.match(path))
    if not state:
        report.ok(f"nothing that changes the state of the project changed against {resolved}")
    elif STATUS_PATH in changed:
        report.ok(f"{len(state)} state-changing file(s) against {resolved}, and {STATUS_PATH} too")
    else:
        report.fail(
            STATUS_PATH,
            f"not touched, although the state of the project changed against {resolved}: "
            + ", ".join(state[:5])
            + (" …" if len(state) > 5 else ""),
        )


def pr_section(body: str) -> tuple[str, bool] | None:
    """The text under `## Needed from the owner`, and whether it is the last section."""
    lines = strip_comments(body).splitlines()
    inside = False
    collected: list[str] = []
    for line in lines:
        if line.startswith("## "):
            if inside:
                return "\n".join(collected).strip(), False
            inside = line[3:].strip().lower() == PR_SECTION
            continue
        if inside:
            collected.append(line)
    return ("\n".join(collected).strip(), True) if inside else None


def check_pull_request(body: str, expected: str, report: Report) -> None:
    print("pull request")
    found = pr_section(body)
    if found is None:
        report.fail("description", "no `## Needed from the owner` section (see the template)")
        return
    section, last = found
    if not last:
        report.fail("description", "`## Needed from the owner` is not the last section")
    elif normalise(expected) in normalise(section):
        report.ok("`## Needed from the owner` is what the register generates, and last")
    else:
        report.fail(
            "description",
            "`## Needed from the owner` differs from what the register generates; "
            "paste the output of `make status`",
        )


# --- main ----------------------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--base", help="commit or branch to compare with (default origin/main)")
    parser.add_argument("--pr-body", type=Path, help="file holding the pull request description")
    parser.add_argument(
        "--print",
        dest="show",
        action="store_true",
        help="print what the register generates for `## Needed from the owner` and exit",
    )
    args = parser.parse_args(argv)

    started = time.monotonic()
    expected = generated(open_records())
    if args.show:
        print(printable(expected))
        return 0

    report = Report()
    if not STATUS.exists():
        report.fail(STATUS_PATH, "missing; the one file that says where the project stands")
    else:
        text = STATUS.read_text(encoding="utf-8")
        found = check_shape(text, report)
        check_milestone(found, report)
        check_pointer(found, report)
    check_freshness(args.base, report)
    if args.pr_body is not None:
        check_pull_request(args.pr_body.read_text(encoding="utf-8"), expected, report)
    print()
    duration = f"{time.monotonic() - started:.2f}s"
    if report.failures:
        print(f"{report.passed} passed, {len(report.failures)} failed in {duration}")
        return 1
    print(f"{report.passed} passed in {duration}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
